PERIPHERALS = pit pwm
DRIVERS = led pacer usb_serial panic
TARGET = racer.bin

SRC = racer.c motors.c motors.h

# Use low level of optimisation to simplify debugging
OPT = -O1

BOARD = racer

include ../../boards/board.mk
